// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygtrgkfudbmizzvpclaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndHJna2Z1ZGJtaXp6dnBjbGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTYzNTAsImV4cCI6MjA3NDQ5MjM1MH0.aPbbnyCeJt5WdnheZVreJDZK96D-YDsqTtqKKubL7ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});